---
description: Pipeline for parsing Cloudflare Sinkhole HTTP logs.
processors:
  - set:
      field: ecs.version
      value: '9.3.0'
  - rename:
      field: message
      target_field: event.original
      ignore_missing: true
      description: Renames the original `message` field to `event.original` to store a copy of the original message. The `event.original` field is not touched if the document already has one; it may happen when Logstash sends the document.
      if: ctx.event?.original == null
  - remove:
      field: message
      ignore_missing: true
      description: The `message` field is no longer required if the document has an `event.original` field.
      if: ctx.event?.original != null
  - json:
      field: event.original
      target_field: json
  - set:
      field: event.kind
      value: event
  - set:
      field: event.category
      value: [network]
  - set:
      field: event.type
      value: [info]
  ## AWS S3 input does _id Based Deduplication and generates "_id" by default.
  ## When "Data Deduplication" is not enabled, this field must be removed.
  ## https://www.elastic.co/docs/reference/beats/filebeat/filebeat-input-aws-s3#_document_id_generation
  - remove:
      field: _id
      description: >
        When data deduplication is disabled, the _id field (used for _id Based Deduplication)
        must be removed.
      if: ctx._conf?.enable_deduplication == false && ctx.input?.type == 'aws-s3'
      ignore_missing: true
  # Timestamp
  - convert:
      field: json.Timestamp
      type: long
      if: ctx.json?.Timestamp != null && ctx.json.Timestamp != ''
      ignore_failure: true
  - script:
      lang: painless
      if: ctx.json?.Timestamp != null && ctx.json.Timestamp instanceof Number
      source: |
        long t = (long)(ctx.json.Timestamp);
        if (t > (long)(1e18)) {
          ctx.json.Timestamp = t/(long)(1e6)
        } else if (t < (long)(1e10))  {
          ctx.json.Timestamp = t*(long)(1e3)
        }
      on_failure:
        - append:
                  field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - date:
      field: json.Timestamp
      if: ctx.json?.Timestamp != null && ctx.json.Timestamp != ''
      formats:
        - UNIX_MS
        - ISO8601
        - yyyy-MM-dd'T'HH:mm:ssZ
      timezone: UTC
      on_failure:
        - append:
                  field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - set:
      field: cloudflare_logpush.sinkhole_http.timestamp
      copy_from: "@timestamp"
      ignore_empty_value: true

  # Handle destination IP
  - convert:
      field: json.DestAddr
      target_field: cloudflare_logpush.sinkhole_http.destination.ip
      type: ip
      ignore_missing: true
      if: ctx.json?.DestAddr != ''
      on_failure:
        - append:
                  field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - set:
      field: destination.ip
      copy_from: cloudflare_logpush.sinkhole_http.destination.ip
      ignore_empty_value: true
  # Geo enrichment (destination IP)
  - geoip:
      field: destination.ip
      target_field: destination.geo
      ignore_missing: true
  - geoip:
      database_file: GeoLite2-ASN.mmdb
      field: destination.ip
      target_field: destination.as
      properties:
        - asn
        - organization_name
      ignore_missing: true
  - rename:
      field: destination.as.asn
      target_field: destination.as.number
      ignore_missing: true
  - rename:
      field: destination.as.organization_name
      target_field: destination.as.organization.name
      ignore_missing: true

  # Handle source IP
  - convert:
      field: json.SrcAddr
      target_field: cloudflare_logpush.sinkhole_http.source.ip
      type: ip
      ignore_missing: true
      if: ctx.json?.SrcAddr != ''
      on_failure:
        - append:
                  field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - set:
      field: source.ip
      copy_from: cloudflare_logpush.sinkhole_http.source.ip
      ignore_empty_value: true
  # Geo enrichment (source IP)
  - geoip:
      field: source.ip
      target_field: source.geo
      ignore_missing: true
  - geoip:
      database_file: GeoLite2-ASN.mmdb
      field: source.ip
      target_field: source.as
      properties:
        - asn
        - organization_name
      ignore_missing: true
  - rename:
      field: source.as.asn
      target_field: source.as.number
      ignore_missing: true
  - rename:
      field: source.as.organization_name
      target_field: source.as.organization.name
      ignore_missing: true

  # HTTP fields
  - rename:
      field: json.Body
      target_field: cloudflare_logpush.sinkhole_http.request.body.content
      ignore_missing: true
  - set:
      field: http.request.body.content
      copy_from: cloudflare_logpush.sinkhole_http.request.body.content
      ignore_empty_value: true
  - convert:
      field: json.BodyLength
      target_field: cloudflare_logpush.sinkhole_http.request.body.bytes
      type: long
      ignore_missing: true
      on_failure:
        - append:
                  field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - set:
      field: http.request.body.bytes
      copy_from: cloudflare_logpush.sinkhole_http.request.body.bytes
      ignore_empty_value: true
  - rename:
      field: json.Method
      target_field: cloudflare_logpush.sinkhole_http.request.method
      ignore_missing: true
  - set:
      field: http.request.method
      copy_from: cloudflare_logpush.sinkhole_http.request.method
      ignore_empty_value: true
  - rename:
      field: json.Referrer
      target_field: cloudflare_logpush.sinkhole_http.request.referrer
      ignore_missing: true
  - set:
      field: http.request.referrer
      copy_from: cloudflare_logpush.sinkhole_http.request.referrer
      ignore_empty_value: true

  - rename:
      field: json.Host
      target_field: cloudflare_logpush.sinkhole_http.host.name
      ignore_missing: true
  - set:
      field: host.name
      copy_from: cloudflare_logpush.sinkhole_http.host.name
      ignore_empty_value: true
  - rename:
      field: json.URI
      target_field: cloudflare_logpush.sinkhole_http.request.uri
      ignore_missing: true
  - rename:
      field: json.URL
      target_field: cloudflare_logpush.sinkhole_http.request.url
      ignore_missing: true
  - uri_parts:
      field: cloudflare_logpush.sinkhole_http.request.url
      target_field: url
      if: ctx.cloudflare_logpush?.sinkhole_http?.request?.url != null && ctx.cloudflare_logpush.sinkhole_http.request.url != ''
  - rename:
      field: json.UserAgent
      target_field: cloudflare_logpush.sinkhole_http.user_agent
      ignore_missing: true
  - user_agent:
      field: cloudflare_logpush.sinkhole_http.user_agent
      ignore_missing: true
  - rename:
      field: json.Username
      target_field: cloudflare_logpush.sinkhole_http.user.name
      ignore_missing: true
  - set:
      field: user.name
      copy_from: cloudflare_logpush.sinkhole_http.user.name
      ignore_empty_value: true

  # Custom fields
  - rename:
      field: json.AccountID
      target_field: cloudflare_logpush.sinkhole_http.account_id
      ignore_missing: true
  - rename:
      field: json.Headers
      target_field: cloudflare_logpush.sinkhole_http.request.headers
      ignore_missing: true
  - split:
      field: cloudflare_logpush.sinkhole_http.request.headers
      separator: '\n'
      ignore_missing: true
  - rename:
      field: json.Password
      target_field: cloudflare_logpush.sinkhole_http.request.password
      ignore_missing: true
  - rename:
      field: json.R2Path
      target_field: cloudflare_logpush.sinkhole_http.r2path
      ignore_missing: true
  - rename:
      field: json.SinkholeID
      target_field: cloudflare_logpush.sinkhole_http.sinkhole_id
      ignore_missing: true

  # Create related fields
  - append:
      field: related.ip
      value: '{{{cloudflare_logpush.sinkhole_http.destination.ip}}}'
      if: ctx.cloudflare_logpush?.sinkhole_http?.destination?.ip != null
      allow_duplicates: false
  - append:
      field: related.ip
      value: '{{{cloudflare_logpush.sinkhole_http.source.ip}}}'
      if: ctx.cloudflare_logpush?.sinkhole_http?.source?.ip != null
      allow_duplicates: false
  - append:
      field: related.hosts
      value: '{{{cloudflare_logpush.sinkhole_http.host.name}}}'
      if: ctx.cloudflare_logpush?.sinkhole_http?.host?.name != null
      allow_duplicates: false
  - append:
      field: related.user
      value: '{{{cloudflare_logpush.sinkhole_http.user.name}}}'
      if: ctx.cloudflare_logpush?.sinkhole_http?.user?.name != null
      allow_duplicates: false

  # Clean resulting event
  - remove:
      field:
        - json
        - _conf
      ignore_missing: true
  - remove:
      field:
        - cloudflare_logpush.sinkhole_http.timestamp
        - cloudflare_logpush.sinkhole_http.destination.ip
        - cloudflare_logpush.sinkhole_http.source.ip
        - cloudflare_logpush.sinkhole_http.request.body.content
        - cloudflare_logpush.sinkhole_http.request.body.bytes
        - cloudflare_logpush.sinkhole_http.request.method
        - cloudflare_logpush.sinkhole_http.request.referrer
        - cloudflare_logpush.sinkhole_http.host.name
        - cloudflare_logpush.sinkhole_http.user.name
        - cloudflare_logpush.sinkhole_http.user_agent
        - cloudflare_logpush.sinkhole_http.request.uri
        - cloudflare_logpush.sinkhole_http.request.url
      if: ctx.tags == null || !(ctx.tags.contains('preserve_duplicate_custom_fields'))
      ignore_missing: true
  - script:
      lang: painless
      description: This script processor iterates over the whole document to remove fields with null values.
      source: |-
        void handleMap(Map map) {
          map.values().removeIf(v -> {
            if (v instanceof Map) {
              handleMap(v);
            } else if (v instanceof List) {
              handleList(v);
            }
            return v == null || v == '' || (v instanceof Map && v.size() == 0) || (v instanceof List && v.size() == 0)
          });
        }
        void handleList(List list) {
          list.removeIf(v -> {
            if (v instanceof Map) {
              handleMap(v);
            } else if (v instanceof List) {
              handleList(v);
            }
            return v == null || v == '' || (v instanceof Map && v.size() == 0) || (v instanceof List && v.size() == 0)
          });
        }
        handleMap(ctx);
  - set:
      field: event.kind
      value: pipeline_error
      if: ctx.error?.message != null
  - append:
      field: tags
      value: preserve_original_event
      allow_duplicates: false
      if: ctx.error?.message != null
on_failure:
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: tags
      value: preserve_original_event
      allow_duplicates: false
