---
description: Pipeline for parsing Cloudflare Audit logs.
processors:
  - set:
      field: ecs.version
      value: '9.3.0'
  - rename:
      field: message
      target_field: event.original
      ignore_missing: true
      description: Renames the original `message` field to `event.original` to store a copy of the original message. The `event.original` field is not touched if the document already has one; it may happen when Logstash sends the document.
      if: ctx.event?.original == null
  - remove:
      field: message
      ignore_missing: true
      description: The `message` field is no longer required if the document has an `event.original` field.
      if: ctx.event?.original != null
  - json:
      field: event.original
      target_field: json
  - set:
      field: event.type
      value: [info]
  - set:
      field: event.kind
      value: event
  - set:
      field: event.category
      value: [authentication]
  ## AWS S3 input does _id Based Deduplication and generates "_id" by default.
  ## When "Data Deduplication" is not enabled, this field must be removed.
  ## https://www.elastic.co/docs/reference/beats/filebeat/filebeat-input-aws-s3#_document_id_generation
  - remove:
      field: _id
      description: >
        When data deduplication is disabled, the _id field (used for _id Based Deduplication)
        must be removed.
      if: ctx._conf?.enable_deduplication == false && ctx.input?.type == 'aws-s3'
      ignore_missing: true
  - convert:
      field: json.When
      type: long
      if: ctx.json?.When != null && ctx.json.When != ''
      ignore_failure: true
  - script:
      lang: painless
      if: ctx.json?.When != null && ctx.json.When instanceof Number
      source: |
        long t = (long)(ctx.json.When);
        if (t > (long)(1e18)) {
          ctx.json.When = t/(long)(1e6)
        } else if (t < (long)(1e10))  {
          ctx.json.When = t*(long)(1e3)
        }
      on_failure:
        - append:
                  field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - date:
      field: json.When
      if: ctx.json?.When != null && ctx.json.When != ''
      formats:
        - UNIX_MS
        - ISO8601
        - yyyy-MM-dd'T'HH:mm:ssZ
      timezone: UTC
      on_failure:
        - append:
                  field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - set:
      field: cloudflare_logpush.audit.timestamp
      copy_from: '@timestamp'
      ignore_failure: true
  - rename:
      field: json.ActionType
      target_field: cloudflare_logpush.audit.action.type
      ignore_missing: true
  - set:
      field: event.action
      copy_from: cloudflare_logpush.audit.action.type
      ignore_failure: true
  - lowercase:
      field: event.action
      ignore_missing: true
  - set:
      field: cloudflare_logpush.audit.action.result
      value: success
      if: ctx.json?.ActionResult == true
  - set:
      field: cloudflare_logpush.audit.action.result
      value: failure
      if: ctx.json?.ActionResult != true
  - set:
      field: event.outcome
      copy_from: cloudflare_logpush.audit.action.result
      ignore_failure: true
  - rename:
      field: json.ActorEmail
      target_field: cloudflare_logpush.audit.actor.email
      ignore_missing: true
  - set:
      field: user.email
      copy_from: cloudflare_logpush.audit.actor.email
      ignore_empty_value: true
  - rename:
      field: json.ActorID
      target_field: cloudflare_logpush.audit.actor.id
      ignore_missing: true
  - set:
      field: user.id
      copy_from: cloudflare_logpush.audit.actor.id
      ignore_empty_value: true
  - convert:
      field: json.ActorIP
      target_field: cloudflare_logpush.audit.actor.ip
      type: ip
      if: ctx.json?.ActorIP != ''
      ignore_missing: true
      on_failure:
        - append:
                  field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - set:
      field: source.ip
      copy_from: cloudflare_logpush.audit.actor.ip
      ignore_empty_value: true
  - rename:
      field: json.ActorType
      target_field: cloudflare_logpush.audit.actor.type
      ignore_missing: true
  - rename:
      field: json.ID
      target_field: cloudflare_logpush.audit.id
      ignore_missing: true
  - set:
      field: event.id
      copy_from: cloudflare_logpush.audit.id
      ignore_empty_value: true
  - rename:
      field: json.Interface
      target_field: cloudflare_logpush.audit.interface
      ignore_missing: true
      if: ctx.json?.Interface != null && ctx.json.Interface != ''
  - set:
      field: event.provider
      copy_from: cloudflare_logpush.audit.interface
      ignore_empty_value: true
  - rename:
      field: json.Metadata
      target_field: cloudflare_logpush.audit.metadata
      ignore_missing: true
  - rename:
      field: json.NewValue
      target_field: cloudflare_logpush.audit.new_value
      if: ctx.json?.NewValue != null
      ignore_missing: true
  - rename:
      field: json.OldValue
      target_field: cloudflare_logpush.audit.old_value
      if: ctx.json?.OldValue != null
      ignore_missing: true
  - rename:
      field: json.OwnerID
      target_field: cloudflare_logpush.audit.owner.id
      ignore_missing: true
  - rename:
      field: json.ResourceID
      target_field: cloudflare_logpush.audit.resource.id
      ignore_missing: true
  - rename:
      field: json.ResourceType
      target_field: cloudflare_logpush.audit.resource.type
      ignore_missing: true
  - append:
      field: related.user
      value: '{{{cloudflare_logpush.audit.actor.id}}}'
      if: ctx.cloudflare_logpush?.audit?.actor?.id != null
      allow_duplicates: false
  - append:
      field: related.user
      value: '{{{cloudflare_logpush.audit.actor.email}}}'
      if: ctx.cloudflare_logpush?.audit?.actor?.email != null
      allow_duplicates: false
  - append:
      field: related.ip
      value: '{{{cloudflare_logpush.audit.actor.ip}}}'
      if: ctx.cloudflare_logpush?.audit?.actor?.ip != null
      allow_duplicates: false
  - append:
      field: related.user
      value: '{{{cloudflare_logpush.audit.owner.id}}}'
      if: ctx.cloudflare_logpush?.audit?.owner?.id != null
      allow_duplicates: false
  - remove:
      field:
        - json
        - _conf
      ignore_missing: true
  - remove:
      field:
        - cloudflare_logpush.audit.timestamp
        - cloudflare_logpush.audit.action.result
        - cloudflare_logpush.audit.action.type
        - cloudflare_logpush.audit.id
        - cloudflare_logpush.audit.interface
        - cloudflare_logpush.audit.actor.ip
        - cloudflare_logpush.audit.actor.email
        - cloudflare_logpush.audit.actor.id
      if: ctx.tags == null || !(ctx.tags.contains('preserve_duplicate_custom_fields'))
      ignore_missing: true
  - script:
      lang: painless
      description: This script processor iterates over the whole document to remove fields with null values.
      source: |-
        void handleMap(Map map) {
          map.values().removeIf(v -> {
            if (v instanceof Map) {
              handleMap(v);
            } else if (v instanceof List) {
              handleList(v);
            }
            return v == null || v == '' || (v instanceof Map && v.size() == 0) || (v instanceof List && v.size() == 0)
          });
        }
        void handleList(List list) {
          list.removeIf(v -> {
            if (v instanceof Map) {
              handleMap(v);
            } else if (v instanceof List) {
              handleList(v);
            }
            return v == null || v == '' || (v instanceof Map && v.size() == 0) || (v instanceof List && v.size() == 0)
          });
        }
        handleMap(ctx);
  - set:
      field: event.kind
      value: pipeline_error
      if: ctx.error?.message != null
  - append:
      field: tags
      value: preserve_original_event
      allow_duplicates: false
      if: ctx.error?.message != null
on_failure:
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.on_failure_pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: tags
      value: preserve_original_event
      allow_duplicates: false
