- name: package
  type: group
  fields:
    - name: architecture
      type: keyword
      external: ecs
    - name: fixed_version
      type: keyword
    - name: name
      type: keyword
      external: ecs
    - name: path
      type: keyword
      external: ecs
    - name: version
      type: keyword
      external: ecs
