fields:
  - name: timestamp
    period: -24h
  - name: attack_campaign_id
    cardinality: 1000
  - name: attack_id
    cardinality: 1000
  - name: colo_country
    cardinality: 200
  - name: colo_geo_hash
    cardinality: 5000
  - name: colo_id
    range:
      min: 1
      max: 1000
  - name: colo_name
    cardinality: 200
  - name: destination_asn
    range:
      min: 1
      max: 65535
  - name: destination_asn_description
    cardinality: 1000
  - name: destination_country
    cardinality: 200
  - name: destination_geo_hash
    cardinality: 5000
  - name: destination_port
    range:
      min: 1
      max: 65535
  - name: direction
    enum: [ingress, egress]
  - name: gre_checksum
    value: 10
  - name: gre_ethertype
    value: 10
  - name: gre_header_length
    value: 1024
  - name: gre_key
    value: 10
  - name: gre_sequence_number
    value: 10
  - name: gre_version
    value: 0
  - name: icmp_checksum
    value: 10
  - name: icmp_code
    value: 10
  - name: icmp_type
    value: 10
  - name: ip_destination_address
    cardinality: 5000
  - name: ip_destination_subnet
    cardinality: 256
  - name: ip_fragment_offset
    value: 0
  - name: ip_header_length
    value: 20
  - name: ip_more_fragments
    value: 0
  - name: ip_protocol
    value: 6
  - name: ip_protocol_name
    enum: [tcp, udp, icmp, gre]
  - name: ip_source_address
    cardinality: 10000
  - name: ip_source_subnet
    cardinality: 256
  - name: ip_total_length
    range:
      min: 20
      max: 65535
  - name: ip_total_length_buckets
    value: 10
  - name: ip_ttl
    range:
      min: 1
      max: 255
  - name: ip_ttl_buckets
    value: 2
  - name: ipv4_checksum
    value: 0
  - name: ipv4_dont_fragment
    value: 0
  - name: ipv4_dscp
    value: 46
  - name: ipv4_ecn
    value: 1
  - name: ipv4_identification
    value: 1
  - name: ipv4_options
    value: 0
  - name: ipv6_dscp
    value: 46
  - name: ipv6_ecn
    value: 1
  - name: ipv6_extension_headers
    cardinality: 100
  - name: ipv6_flow_label
    value: 1
  - name: ipv6_identification
    value: 1
  - name: mitigation_reason
    enum: [BLOCKED, ALLOWED, UNKNOWN]
  - name: mitigation_scope
    enum: [local, global]
  - name: mitigation_system
    enum: [flowtrackd, dosd, magic-firewall]
  - name: outcome
    enum: [pass, drop]
  - name: protocol_state
    enum: [OPEN, CLOSED, ESTABLISHED, SYN_SENT, SYN_RECEIVED, FIN_WAIT]
  - name: rule_id
    cardinality: 1000
  - name: ruleset_id
    cardinality: 100
  - name: ruleset_override_id
    cardinality: 100
  - name: sample_interval
    value: 1
  - name: source_asn
    range:
      min: 1
      max: 65535
  - name: source_asn_description
    cardinality: 1000
  - name: source_country
    cardinality: 200
  - name: source_geo_hash
    cardinality: 5000
  - name: source_port
    range:
      min: 1
      max: 65535
  - name: tcp_acknowledgement_number
    value: 1000
  - name: tcp_checksum
    value: 10
  - name: tcp_data_offset
    value: 0
  - name: tcp_flags
    value: 1
  - name: tcp_flags_string
    cardinality: 100
  - name: tcp_mss
    value: 512
  - name: tcp_options
    cardinality: 50
  - name: tcp_sack_blocks
    value: 1
  - name: tcp_sacks_permitted
    value: 1
  - name: tcp_sequence_number
    value: 100
  - name: tcp_timestamp_ecr
    value: 100
  - name: tcp_timestamp_value
    value: 100
  - name: tcp_urgent_pointer
    value: 0
  - name: tcp_window_scale
    value: 10
  - name: tcp_window_size
    value: 10
  - name: udp_checksum
    value: 10
  - name: udp_payload_length
    value: 10
  - name: verdict
    enum: [pass, drop]
