rules:
  - path: /vm/v4/integration/assets
    methods: ["POST"]
    responses:
      - status_code: 200
        body: |-
          {{ minify_json `
          {
            "data": [
              {
                "assessed_for_policies": false,
                "assessed_for_vulnerabilities": true,
                "credential_assessments": [
                  {
                    "port": 22,
                    "protocol": "TCP",
                    "status": "NO_CREDS_SUPPLIED"
                  }
                ],
                "critical_vulnerabilities": 1,
                "exploits": 1,
                "id": "8bcfe121-1234-5678-9012-c4a6abcdabcde-default-asset-4",
                "ip": "175.16.199.1",
                "last_assessed_for_vulnerabilities": "2025-05-08T06:51:31.736Z",
                "last_scan_end": "2025-05-08T06:51:31.736Z",
                "last_scan_start": "2025-05-08T06:51:19.193Z",
                "mac": "00:00:5E:00:53:00",
                "malware_kits": 0,
                "moderate_vulnerabilities": 0,
                "os_architecture": "",
                "os_description": "Ubuntu Linux",
                "os_family": "Linux",
                "os_name": "Linux",
                "os_system_name": "Ubuntu Linux",
                "os_type": "",
                "os_vendor": "Ubuntu",
                "risk_score": 1268,
                "severe_vulnerabilities": 1,
                "tags": [
                  {
                    "name": "test",
                    "type": "SITE"
                  }
                ],
                "total_vulnerabilities": 2,
                "unique_identifiers": [],
                "new": [],
                "remediated": [],
                "same": [
                  {
                    "check_id": null,
                    "first_found": "2025-05-08T06:51:31Z",
                    "key": "",
                    "last_found": "2025-05-08T06:51:31.736Z",
                    "nic": null,
                    "port": 22,
                    "proof": "<p><ul><li>Running SSH service</li><li>Product OpenSSH exists -- OpenBSD OpenSSH 8.9p1</li><li>Vulnerable version of product OpenSSH found -- OpenBSD OpenSSH 8.9p1</li></ul><p>Vulnerable version of OpenSSH detected on Ubuntu Linux</p></p>",
                    "protocol": "TCP",
                    "solution_fix": "<p>Download and apply the upgrade from: <a href=\"https://ftp.openbsd.org/pub/OpenBSD/OpenSSH\">https://ftp.openbsd.org/pub/OpenBSD/OpenSSH</a></p>",
                    "solution_id": "openbsd-openssh-upgrade-latest",
                    "solution_summary": "Upgrade to the latest version of OpenSSH",
                    "solution_type": "rollup",
                    "status": "VULNERABLE_VERS",
                    "vulnerability_id": "openbsd-openssh-cve-2024-6387"
                  },
                  {
                    "check_id": null,
                    "first_found": "2025-05-08T06:51:31Z",
                    "key": "",
                    "last_found": "2025-05-08T06:51:31.736Z",
                    "nic": null,
                    "port": 22,
                    "proof": "<p><ul><li>Running SSH service</li><li>Insecure MAC algorithms in use: hmac-sha1,umac-64@openssh.com</li></ul></p>",
                    "protocol": "TCP",
                    "solution_fix": "<p>Consult the product documentation for instructions to disable any insecure MD5 or 96-bit HMAC algorithms within the SSH configuration.</p>",
                    "solution_id": "ssh-weak-message-authentication-code-algorithms",
                    "solution_summary": "Disable any MD5 or 96-bit HMAC algorithms within the SSH configuration",
                    "solution_type": "workaround",
                    "status": "VULNERABLE_VERS",
                    "vulnerability_id": "ssh-weak-message-authentication-code-algorithms"
                  }
                ]
              },
              {
                "assessed_for_policies": false,
                "assessed_for_vulnerabilities": true,
                "critical_vulnerabilities": 0,
                "exploits": 0,
                "id": "452534235-25a7-40a3-9321-28ce0b5cc90e-default-asset-199",
                "ip": "10.1.0.128",
                "last_assessed_for_vulnerabilities": "2020-03-20T19:19:42.611Z",
                "last_scan_end": "2020-03-20T19:19:42.611Z",
                "last_scan_start": "2020-03-20T19:18:13.611Z",
                "malware_kits": 0,
                "moderate_vulnerabilities": 2,
                "os_architecture": "x86_64",
                "os_description": "CentOS Linux 2.6.18",
                "os_family": "Linux",
                "os_name": "Linux",
                "os_system_name": "CentOS Linux",
                "os_type": "General",
                "os_vendor": "CentOS",
                "os_version": "2.6.18",
                "risk_score": 0,
                "severe_vulnerabilities": 0,
                "tags": [
                  {
                    "name": "lab",
                    "type": "SITE"
                  }
                ],
                "total_vulnerabilities": 2,
                "new": [],
                "remediated": []
              }
            ],
            "metadata": {
              "number": 0,
              "size": 2,
              "totalResources": 2195,
              "totalPages": 1098,
              "cursor": null
            },
            "links": [
              {
                "href": "https://us.api.insight.rapid7.com:443/vm/v4/integration/assets?page=0&size=2",
                "rel": "first"
              },
              {
                "href": "https://us.api.insight.rapid7.com:443/vm/v4/integration/assets?page=0&size=2",
                "rel": "self"
              },
              {
                "href": "https://us.api.insight.rapid7.com:443/vm/v4/integration/assets?page=1&size=2&cursor=1542252837:::_S:::12474375-34a7-40a3-9821-28db0b5cc90e-default-asset-10",
                "rel": "next"
              },
              {
                "href": "https://us.api.insight.rapid7.com:443/vm/v4/integration/assets?page=1097&size=2",
                "rel": "last"
              }
            ]
          }
          `}}
  - path: /vm/v4/integration/vulnerabilities
    methods: ["POST"]
    responses:
      - status_code: 200
        body: |-
          {{ minify_json `
          {
            "data": [
              {
                "added": "2018-05-16T00:00:00Z",
                "categories": "7-Zip",
                "cves": "CVE-2008-6536",
                "cvss_v2_access_complexity": "low",
                "cvss_v2_access_vector": "network",
                "cvss_v2_authentication": "none",
                "cvss_v2_availability_impact": "complete",
                "cvss_v2_confidentiality_impact": "complete",
                "cvss_v2_exploit_score": 9.996799,
                "cvss_v2_impact_score": 10.000845,
                "cvss_v2_integrity_impact": "complete",
                "cvss_v2_score": 10,
                "cvss_v2_vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
                "cvss_v3_attack_complexity": null,
                "cvss_v3_attack_vector": null,
                "cvss_v3_availability_impact": null,
                "cvss_v3_confidentiality_impact": null,
                "cvss_v3_exploit_score": 0,
                "cvss_v3_impact_score": 0,
                "cvss_v3_integrity_impact": null,
                "cvss_v3_privileges_required": null,
                "cvss_v3_scope": null,
                "cvss_v3_score": 0,
                "cvss_v3_user_interaction": null,
                "cvss_v3_vector": null,
                "denial_of_service": false,
                "description": "Unspecified vulnerability in 7-zip before 4.5.7 has unknown impact and remote attack vectors, as demonstrated by the PROTOS GENOME test suite for Archive Formats (c10).",
                "exploits": [],
                "id": "7-zip-cve-2008-6536",
                "links": [
                  {
                    "href": "http://www.securityfocus.com/bid/28285",
                    "id": "28285",
                    "rel": "advisory",
                    "source": "bid"
                  },
                  {
                    "href": "https://exchange.xforce.ibmcloud.com/vulnerabilities/41247",
                    "id": "41247",
                    "rel": "advisory",
                    "source": "xf"
                  },
                  {
                    "href": "http://nvd.nist.gov/vuln/detail/CVE-2008-6536",
                    "id": "CVE-2008-6536",
                    "rel": "advisory",
                    "source": "cve"
                  },
                  {
                    "href": "http://www.cert.fi/haavoittuvuudet/joint-advisory-archive-formats.html",
                    "id": "http://www.cert.fi/haavoittuvuudet/joint-advisory-archive-formats.html",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "http://www.ee.oulu.fi/research/ouspg/protos/testing/c10/archive/",
                    "id": "http://www.ee.oulu.fi/research/ouspg/protos/testing/c10/archive/",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "http://www.securityfocus.com/bid/28285",
                    "id": "http://www.securityfocus.com/bid/28285",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "http://www.vupen.com/english/advisories/2008/0914/references",
                    "id": "http://www.vupen.com/english/advisories/2008/0914/references",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "http://www.xerox.com/download/security/security-bulletin/16287-4d6b7b0c81f7b/cert_XRX13-003_v1.0.pdf",
                    "id": "http://www.xerox.com/download/security/security-bulletin/16287-4d6b7b0c81f7b/cert_XRX13-003_v1.0.pdf",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "https://exchange.xforce.ibmcloud.com/vulnerabilities/41247",
                    "id": "https://exchange.xforce.ibmcloud.com/vulnerabilities/41247",
                    "rel": "advisory",
                    "source": "url"
                  }
                ],
                "malware_kits": [],
                "modified": "2018-06-08T00:00:00Z",
                "pci_cvss_score": 10,
                "pci_fail": true,
                "pci_severity_score": 5,
                "pci_special_notes": "",
                "pci_status": "fail",
                "published": "2009-03-29T00:00:00Z",
                "references": "bid:28285,xf:41247,cve:CVE-2008-6536,url:http://www.cert.fi/haavoittuvuudet/joint-advisory-archive-formats.html,url:http://www.ee.oulu.fi/research/ouspg/protos/testing/c10/archive/,url:http://www.securityfocus.com/bid/28285,url:http://www.vupen.com/english/advisories/2008/0914/references,url:http://www.xerox.com/download/security/security-bulletin/16287-4d6b7b0c81f7b/cert_XRX13-003_v1.0.pdf,url:https://exchange.xforce.ibmcloud.com/vulnerabilities/41247",
                "risk_score": 885.16,
                "severity": "critical",
                "severity_score": 10,
                "title": "7-Zip: CVE-2008-6536: Unspecified vulnerability in 7-zip before 4.5.7"
              },
              {
                "added": "2018-05-16T00:00:00Z",
                "categories": "7-Zip,Remote Execution",
                "cves": "CVE-2016-2334",
                "cvss_v2_access_complexity": "medium",
                "cvss_v2_access_vector": "network",
                "cvss_v2_authentication": "none",
                "cvss_v2_availability_impact": "complete",
                "cvss_v2_confidentiality_impact": "complete",
                "cvss_v2_exploit_score": 8.5888,
                "cvss_v2_impact_score": 10.000845,
                "cvss_v2_integrity_impact": "complete",
                "cvss_v2_score": 9.3,
                "cvss_v2_vector": "AV:N/AC:M/Au:N/C:C/I:C/A:C",
                "cvss_v3_attack_complexity": "low",
                "cvss_v3_attack_vector": "local",
                "cvss_v3_availability_impact": "high",
                "cvss_v3_confidentiality_impact": "high",
                "cvss_v3_exploit_score": 1.8345766,
                "cvss_v3_impact_score": 5.873119,
                "cvss_v3_integrity_impact": "high",
                "cvss_v3_privileges_required": "none",
                "cvss_v3_scope": "unchanged",
                "cvss_v3_score": 7.8,
                "cvss_v3_user_interaction": "required",
                "cvss_v3_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "denial_of_service": false,
                "description": "Heap-based buffer overflow in the NArchive::NHfs::CHandler::ExtractZlibFile method in 7zip before 16.00 and p7zip allows remote attackers to execute arbitrary code via a crafted HFS+ image.",
                "exploits": [],
                "id": "7-zip-cve-2016-2334",
                "links": [
                  {
                    "href": "http://www.securityfocus.com/bid/90531",
                    "id": "90531",
                    "rel": "advisory",
                    "source": "bid"
                  },
                  {
                    "href": "http://nvd.nist.gov/vuln/detail/CVE-2016-2334",
                    "id": "CVE-2016-2334",
                    "rel": "advisory",
                    "source": "cve"
                  },
                  {
                    "href": "http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html",
                    "id": "http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "http://blog.talosintelligence.com/2017/11/exploiting-cve-2016-2334.html",
                    "id": "http://blog.talosintelligence.com/2017/11/exploiting-cve-2016-2334.html",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "http://www.oracle.com/technetwork/topics/security/bulletinoct2016-3090566.html",
                    "id": "http://www.oracle.com/technetwork/topics/security/bulletinoct2016-3090566.html",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "http://www.securityfocus.com/bid/90531",
                    "id": "http://www.securityfocus.com/bid/90531",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "http://www.securitytracker.com/id/1035876",
                    "id": "http://www.securitytracker.com/id/1035876",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "http://www.talosintel.com/reports/TALOS-2016-0093/",
                    "id": "http://www.talosintel.com/reports/TALOS-2016-0093/",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNYIQAU3FKFBNFPK6GKYTSVRHQA7PTYT/",
                    "id": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNYIQAU3FKFBNFPK6GKYTSVRHQA7PTYT/",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DTGWICT3KYYDPDXRNO5SXD32GZICGRIR/",
                    "id": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DTGWICT3KYYDPDXRNO5SXD32GZICGRIR/",
                    "rel": "advisory",
                    "source": "url"
                  },
                  {
                    "href": "https://security.gentoo.org/glsa/201701-27",
                    "id": "https://security.gentoo.org/glsa/201701-27",
                    "rel": "advisory",
                    "source": "url"
                  }
                ],
                "malware_kits": [],
                "modified": "2018-06-08T00:00:00Z",
                "pci_cvss_score": 9.3,
                "pci_fail": true,
                "pci_severity_score": 5,
                "pci_special_notes": "",
                "pci_status": "fail",
                "published": "2016-12-13T00:00:00Z",
                "references": "bid:90531,cve:CVE-2016-2334,url:http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html,url:http://blog.talosintelligence.com/2017/11/exploiting-cve-2016-2334.html,url:http://www.oracle.com/technetwork/topics/security/bulletinoct2016-3090566.html,url:http://www.securityfocus.com/bid/90531,url:http://www.securitytracker.com/id/1035876,url:http://www.talosintel.com/reports/TALOS-2016-0093/,url:https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DNYIQAU3FKFBNFPK6GKYTSVRHQA7PTYT/,url:https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DTGWICT3KYYDPDXRNO5SXD32GZICGRIR/,url:https://security.gentoo.org/glsa/201701-27",
                "risk_score": 582.82,
                "severity": "critical",
                "severity_score": 9,
                "title": "7-Zip: CVE-2016-2334: Heap-based buffer overflow vulnerability"
              }
            ],
            "metadata": {
              "number": 0,
              "size": 2,
              "totalResources": 81631,
              "totalPages": 40816,
              "cursor": "-37745434:::_S:::7-zip-cve-2016-2334"
            },
            "links": [
              {
                "href": "https://us.api.insight.rapid7.com:443/vm/v4/integration/vulnerabilities?page=0&size=2&sort=id,asc",
                "rel": "first"
              },
              {
                "href": "https://us.api.insight.rapid7.com:443/vm/v4/integration/vulnerabilities?page=0&size=2&sort=id,asc",
                "rel": "self"
              },
              {
                "href": "https://us.api.insight.rapid7.com:443/vm/v4/integration/vulnerabilities?page=1&size=2&sort=id,asc&cursor=-37745434:::_S:::7-zip-cve-2016-2334",
                "rel": "next"
              },
              {
                "href": "https://us.api.insight.rapid7.com:443/vm/v4/integration/vulnerabilities?page=40815&size=2&sort=id,asc",
                "rel": "last"
              }
            ]
          }
          `}}
